name: task - validate commit on main
on:
  push:
    branches: [ main ]

jobs:
#  assemble:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: read
#      packages: write
#
#    steps:
#      - name: Setup actions.
#        uses: actions/checkout@v2
#
#      - name: set up JDK 11
#        uses: actions/setup-java@v2
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: gradle
#
#      - name: Run Unit Tests
#        if: always()
#        run: ./gradlew testDebugUnitTest
#
#      - name: Generate AAR and APK files
#        if: always()
#        run: ./gradlew assembleDebug
#
#      - name: Upload AAR files
#        if: always()
#        uses: actions/upload-artifact@v2
#        with:
#          name: apk.zip
#          path: |
#            app/build/outputs/apk/debug/app-debug.apk
#            swap_estate/build/outputs/aar
#
#
#
#  detekt:
#    runs-on: ubuntu-latest
#    steps:
#      - name: "checkout"
#        uses: actions/checkout@v2
#      - name: "detekt"
#        run: ./gradlew detekt
#
#      - name: Upload detekt results
#        if: always()
#        uses: actions/upload-artifact@v2
#        with:
#          name: detekt_results
#          path: app/build/reports/detekt

  test:
    runs-on: macos-latest
#    needs: assemble
    strategy:
      matrix:
        api-level: [ 29 ]
        target: [ default ]
    steps:
      - name: Copy gradle properties file
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86
          profile: Nexus 6
          script: ./gradlew connectedCheck --stacktrace



            
